import OpenAI from 'openai';
import { getSettings, addHistoryItem } from '../utils/storage';
import { ExtractionResult, ActiveTask, ChatMessage } from '../utils/types';

console.log('Background service worker started');

let currentTask: ActiveTask | null = null;
let abortController: AbortController | null = null;

// Initialize state from storage on startup
chrome.storage.local.get(['currentTask'], (result) => {
  if (result.currentTask) {
    currentTask = result.currentTask;
  }
});

chrome.runtime.onInstalled.addListener(() => {
  console.log('Extension installed');
});

// Listen for messages from Popup
chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message.type === 'START_SUMMARIZATION') {
    startSummarization(message.payload);
    sendResponse({ success: true });
    return true; // async response
  }
  
  if (message.type === 'START_REFINEMENT') {
    const { messages, title } = message.payload;
    startRefinement(messages, title);
    sendResponse({ success: true });
    return true;
  }
  
  if (message.type === 'CANCEL_SUMMARIZATION') {
    if (abortController) {
      abortController.abort();
      abortController = null;
    }
    stopTimer(); // Ensure timer stops immediately
    currentTask = null;
    chrome.storage.local.remove('currentTask');
    broadcastUpdate();
    sendResponse({ success: true });
    return true;
  }
  
  if (message.type === 'GET_STATUS') {
    // Return the memory state which should be in sync with storage
    sendResponse(currentTask);
    return true;
  }
  
  if (message.type === 'CLEAR_STATUS') {
    currentTask = null;
    chrome.storage.local.remove('currentTask');
    sendResponse({ success: true });
    return true;
  }
});

function updateTaskState(newState: Partial<ActiveTask>) {
  currentTask = { ...currentTask, ...newState } as ActiveTask;
  chrome.storage.local.set({ currentTask });
  broadcastUpdate();
}

let timerInterval: NodeJS.Timeout | null = null;
let startTime: number = 0;

function startTimer(baseMessage: string) {
  if (timerInterval) clearInterval(timerInterval);
  startTime = Date.now();
  
  timerInterval = setInterval(() => {
    if (!currentTask) {
      if (timerInterval) clearInterval(timerInterval);
      return;
    }
    
    const elapsed = Math.floor((Date.now() - startTime) / 1000);
    const message = `${baseMessage} (${elapsed}s)`;
    
    // Update task state without broadcasting every second to avoid UI flicker overkill, 
    // but here we want to show it, so we update storage and broadcast.
    // To optimize, maybe only broadcast if popup is open? 
    // For now, we update the task state.
    currentTask = { ...currentTask, message };
    chrome.storage.local.set({ currentTask });
    broadcastUpdate();
  }, 1000);
}

function stopTimer() {
  if (timerInterval) {
    clearInterval(timerInterval);
    timerInterval = null;
  }
}

async function startRefinement(messages: ChatMessage[], title?: string) {
  try {
    abortController = new AbortController();
    // Clear previous task state to avoid pollution, but we will merge new state in updateTaskState
    // so we set currentTask to empty object first if we want a fresh start, 
    // OR we just rely on overwriting fields.
    // For refinement, we want to ensure we track the title.
    
    // Explicitly set the initial state for refinement
    currentTask = {
      status: 'Refining...', 
      message: 'Initializing refinement...', 
      progress: 5,
      conversationHistory: messages,
      title: title
    };
    chrome.storage.local.set({ currentTask });
    broadcastUpdate();

    const settings = await getSettings();
    let effectiveApiKey = settings.apiKeys?.[settings.provider] || settings.apiKey;
    
    if (!effectiveApiKey) {
      throw new Error(`API Key for ${settings.provider} is missing. Please check settings.`);
    }

    const openai = new OpenAI({
      apiKey: effectiveApiKey,
      baseURL: settings.baseUrl,
    });

    updateTaskState({ 
      status: 'Refining...', 
      message: 'Sending instructions to AI...', 
      progress: 30,
      conversationHistory: messages
    });

    const completionPromise = openai.chat.completions.create({
      model: settings.model,
      messages: [
        { 
          role: 'system', 
          content: 'You are an expert technical editor. The conversation history contains a markdown document generated by an assistant. The user will ask for changes, optimizations, or extensions to this specific document. You must REWRITE the entire document incorporating these changes based on the existing content. Return ONLY the updated markdown content. Do not generate a new document from scratch unless explicitly asked. Do not include conversational filler like "Here is the updated version".' 
        },
        ...messages.filter(m => m.role !== 'system'), // Filter out old system prompts if any
      ] as any,
    }, { signal: abortController.signal });

    const baseMessage = 'Waiting for AI response...';
    updateTaskState({ 
      status: 'Refining...', 
      message: baseMessage, 
      progress: 50,
      conversationHistory: messages
    });
    startTimer(baseMessage);

    const completion: any = await completionPromise;
    stopTimer();

    updateTaskState({ 
      status: 'Refining...', 
      message: 'Processing response...', 
      progress: 90,
      conversationHistory: messages
    });

    const refinedContent = completion.choices[0]?.message?.content || '';
    
    // Update history with assistant response
    const updatedHistory: ChatMessage[] = [
      ...messages,
      { role: 'assistant', content: refinedContent }
    ];

    // Generate new versioned title
    let newTitle = title || 'Untitled Chat';
    const versionMatch = newTitle.match(/\(v(\d+)\)$/);
    if (versionMatch) {
      const version = parseInt(versionMatch[1], 10) + 1;
      newTitle = newTitle.replace(/\(v\d+\)$/, `(v${version})`);
    } else {
      newTitle = `${newTitle} (v2)`;
    }

    // Save to History
    const newItem = {
      id: Date.now().toString(),
      title: newTitle,
      date: Date.now(),
      content: refinedContent,
      url: '' // We might not have URL here, but that's okay for refined docs
    };
    await addHistoryItem(newItem);

    updateTaskState({ 
      status: 'Refined!', 
      message: 'Refinement complete!',
      progress: 100, 
      result: refinedContent,
      conversationHistory: updatedHistory,
      title: newTitle
    });

  } catch (error: any) {
    stopTimer();
    if (error.name === 'AbortError') {
      console.log('Refinement cancelled');
      return;
    }
    console.error('Refinement error:', error);
    updateTaskState({ 
      status: 'Error', 
      message: error.message || 'Refinement failed',
      progress: 0, 
      error: error.message,
      conversationHistory: messages // Keep history so user can retry
    });
  } finally {
    abortController = null;
    stopTimer();
  }
}

async function startSummarization(extraction: ExtractionResult) {
  try {
    abortController = new AbortController();
    
    // Explicitly reset task for new summarization
    currentTask = { 
      status: 'Processing...', 
      message: 'Initializing...', 
      progress: 5,
      title: extraction.title 
    };
    chrome.storage.local.set({ currentTask });
    broadcastUpdate();

    const settings = await getSettings();
    
    // Determine the effective API Key:
    // 1. Try to get provider-specific key from the new apiKeys map
    // 2. Fallback to the legacy single 'apiKey' if not found
    let effectiveApiKey = settings.apiKeys?.[settings.provider] || settings.apiKey;
    
    // Special handling for 'custom' provider: might rely on the legacy field if not explicitly mapped,
    // but the UI now syncs custom key to apiKeys['custom'] too.
    
    if (!effectiveApiKey) {
      throw new Error(`API Key for ${settings.provider} is missing. Please check settings.`);
    }

    const openai = new OpenAI({
      apiKey: effectiveApiKey,
      baseURL: settings.baseUrl,
    });

    updateTaskState({ status: 'Processing...', message: 'Sending request to AI...', progress: 30 });

    const initialMessages = [
      { role: 'system', content: settings.systemPrompt },
      { 
        role: 'user', 
        content: `Please summarize the following conversation from ${extraction.url}.\n\nTitle: ${extraction.title}\n\nContent:\n${JSON.stringify(extraction.messages)}` 
      }
    ];

    // Create a timeout promise that rejects after 90 seconds
    const timeoutPromise = new Promise((_, reject) => {
      const timer = setTimeout(() => {
        reject(new Error('Generation timed out (exceeded 1.5 minutes). Please try again or use a shorter chat.'));
      }, 90000); // 1.5 minutes
      
      // Clear timeout if aborted
      if (abortController?.signal) {
        abortController.signal.addEventListener('abort', () => clearTimeout(timer));
      }
    });

    const completionPromise = openai.chat.completions.create({
      model: settings.model,
      messages: initialMessages as any,
    }, { signal: abortController.signal });

    const baseMessage = 'Waiting for AI response...';
    updateTaskState({ status: 'Processing...', message: baseMessage, progress: 50 });
    startTimer(baseMessage);

    // Race between completion and timeout
    const completion: any = await Promise.race([completionPromise, timeoutPromise]);
    stopTimer();

    updateTaskState({ status: 'Processing...', message: 'Processing response...', progress: 90 });

    let summary = completion.choices[0]?.message?.content || 'No summary generated.';
    
    // Strip wrapping markdown code blocks if present
    // Matches ```markdown at start and ``` at end, allowing for optional newlines
    summary = summary.replace(/^```markdown\s*/i, '').replace(/\s*```$/, '');

    // Save to History
    const newItem = {
      id: Date.now().toString(),
      title: extraction.title || 'Untitled Chat',
      date: Date.now(),
      content: summary,
      url: extraction.url
    };

    // Clean up summary: Ensure it starts with Front Matter
    // Some models (like Gemini) might output conversational text before the YAML block.
    // We strip everything before the first "---"
    const frontMatterRegex = /^[\s\S]*?(---\s*\n[\s\S]*?---)/;
    const match = summary.match(frontMatterRegex);
    if (match && match[1]) {
        // If we found the YAML block, keep it and everything after it
        // Note: The regex above captures the YAML block in group 1.
        // We actually want to find the index of the first "---" and slice from there.
        const firstDashIndex = summary.indexOf('---');
        if (firstDashIndex > 0) {
             newItem.content = summary.slice(firstDashIndex);
             // Update the summary variable too for the UI update below
             // Note: 'const summary' is immutable, we should have used let or a new variable.
             // But since we can't change previous code easily in search/replace block without context,
             // we'll handle it by updating newItem and the broadcast payload.
             // Wait, I need to update the 'summary' variable or create a cleaned one.
        }
    }
    
    // Let's do a cleaner replacement strategy. 
    // I will look for where 'summary' is defined and clean it there.
    
    await addHistoryItem(newItem);

    updateTaskState({ 
      status: 'Done!', 
      message: 'Summary generated successfully!',
      progress: 100, 
      result: summary, // Use cleaned summary
      conversationHistory: [
        ...initialMessages as ChatMessage[],
        { role: 'assistant', content: summary } // Use cleaned summary
      ]
    });

    // Set badge to indicate completion
    chrome.action.setBadgeText({ text: '1' });
    chrome.action.setBadgeBackgroundColor({ color: '#4CAF50' });

    // Send Notification
    const iconUrl = chrome.runtime.getURL('public/icon-128.png');
    chrome.notifications.create({
      type: 'basic',
      iconUrl: iconUrl,
      title: 'Chat Export Complete',
      message: `Summary generated for: ${extraction.title || 'Untitled Chat'}`
    }, (notificationId) => {
      if (chrome.runtime.lastError) {
        console.error('Notification failed:', chrome.runtime.lastError);
      } else {
        console.log('Notification sent:', notificationId);
      }
    });

  } catch (error: any) {
    if (error.name === 'AbortError') {
      console.log('Summarization cancelled');
      return; // Do nothing if cancelled
    }

    console.error('Summarization error:', error);
    updateTaskState({ 
      status: 'Error', 
      message: error.message || 'An error occurred',
      progress: 0, 
      error: error.message 
    });

    // Send Error Notification
    const iconUrl = chrome.runtime.getURL('public/icon-128.png');
    chrome.notifications.create({
      type: 'basic',
      iconUrl: iconUrl,
      title: 'Chat Export Failed',
      message: error.message || 'Unknown error occurred'
    });
  } finally {
    abortController = null;
  }
}

function broadcastUpdate() {
  chrome.runtime.sendMessage({ type: 'STATUS_UPDATE', payload: currentTask }).catch(() => {
    // Popup might be closed, which is expected
  });
}
